repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    #   - id: trailing-whitespace
    #   - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Complete hooks with https://pre-commit.com/hooks.html
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      # - id: go-err-check # requires github.com/kisielk/errcheck
      # - id: go-static-check # install https://staticcheck.io/docs/
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        args: [--config=.github/linters/.golangci.yml] # optional
    #   - id: go-ruleguard # requires https://github.com/quasilyte/go-ruleguard
    #     args: [rules/rules.go] # required 
    
  - repo: https://github.com/sgaunet/pre-commit
    rev: v0.1.0
    hooks:
    -   id: osv-scanner